apiVersion: v1
kind: Service
metadata:
  name: aksarcdemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007 # Optional: You can remove this line if you want Kubernetes to automatically assign a port
  selector:
    app: aksarcdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksarcdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksarcdemo
  template:
    metadata:
      labels:
        app: aksarcdemo
    spec:
      containers:
      - name: aksarcdemo
        image: nnamuhcs/finalaksarcdemo:latest
        ports:
        - containerPort: 8080
